SELECT
    PRODUCT.PRODUCT_CODE,
    SUM(PRODUCT.PRICE * OFFLINE_SALE.SALES_AMOUNT) AS SALES
FROM OFFLINE_SALE
INNER JOIN PRODUCT
    ON OFFLINE_SALE.PRODUCT_ID = PRODUCT.PRODUCT_ID
GROUP BY PRODUCT.PRODUCT_CODE
ORDER BY SUM(PRODUCT.PRICE * OFFLINE_SALE.SALES_AMOUNT) DESC, PRODUCT.PRODUCT_CODE;
